default: &default
  application_access_key: <%= ENV['UNSPLASH_APPLICATION_ACCESS_KEY'] %>
  application_secret: <%= ENV['UNSPLASH_APPLICATION_SECRET'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
